mysite/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mysite/goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>', views.product_detail, name='product_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls'), name='goods'),
    path('cart/', include('cart.urls'), name='cart'),
    path('orders/', include('orders.urls', namespace='orders')),
]

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

mysite/goods/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена товара')

    def __str__(self):
        return f'{self.name} - {self.price} руб.'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

mysite/orders/models.py
from django.db import models
from goods.models import Product
from phonenumber_field.modelfields import PhoneNumberField


class Order(models.Model):
    name = models.CharField(max_length=128, verbose_name='Имя')
    phone = PhoneNumberField(blank=True, verbose_name='Номер телефона', help_text='В формате: +79008007766')
    region = models.CharField(max_length=128, verbose_name='Регион')
    city = models.CharField(max_length=128, verbose_name='Город')
    street_name = models.CharField(max_length=128, verbose_name='Улица')
    house_number = models.CharField(max_length=8, verbose_name='Номер дома')
    case_number = models.CharField(max_length=8, blank=True, verbose_name='Корпус')
    apartment_number = models.CharField(max_length=8, verbose_name='Номер квартиры')
    postal_code = models.IntegerField(verbose_name='Почтовый индекс')
    paid = models.BooleanField(default=False, verbose_name='Оплачено')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

mysite/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'phone', 'region', 'city', 'street_name', 'house_number',
                  'case_number', 'apartment_number', 'postal_code']

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from goods.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/goods/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from cart.forms import CartAddProductForm
from .models import Product


def product_list(request):
    products = get_list_or_404(Product)
    return render(request, 'goods/product/list.html', {'products': products})


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    return render(request, 'goods/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

mysite/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

mysite/cart/templates/cart/detail.html
{% extends "goods/base.html" %}
{% block title %}
<title>Корзина</title>
{% endblock %}
{% block content %}
    <h1>Корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за шт.</th>
            <th>Стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">удалить</a></td>
                    <td class="num">{{ item.price }} руб.</td>
                    <td class="num">{{ item.total_price }} руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итог</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'goods:product_list' %}" class="button light">Вернуться в магазин</a>
        <a href="{% url 'orders:order_create' %}" class="button">Оформить заказ</a>
    </p>
{% endblock %}

mysite/goods/templates/goods/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    {% block title %}
    {% endblock %}
</head>
<body>
<div id="header">
    <a href="/" class="logo">Магазин</a>
</div>
<div id="subheader">
    <a href="/cart" class="cart">Корзина</a>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

mysite/goods/templates/goods/product/detail.html
{% extends "goods/base.html" %}
{% block title %}
<title>{{ product.name }}</title>
{% endblock %}
{% block content %}
    <p class="price">{{ product.price }} руб.</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>
{% endblock %}

mysite/goods/templates/goods/product/list.html
{% extends "goods/base.html" %}
{% block title %}
<title>Магазин</title>
{% endblock %}
{% block content %}
    <div id="main" class="product-list">
        <h1>Магазин</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.id }}">{{ product.name }}</a><br>
                {{ product.price }} руб.
            </div>
        {% endfor %}
    </div>
{% endblock %}

mysite/orders/templates/orders/order/create.html
{% extends "goods/base.html" %}

{% block title %}
Оформление заказа
{% endblock %}

{% block content %}
    <h1>Оформление заказа</h1>
    <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>{{ item.total_price }} руб.</span>
                </li>
            {% endfor %}
        </ul>
        <p>Итог: {{ cart.get_total_price }} руб.</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Оформить заказ"></p>
        {% csrf_token %}
    </form>
{% endblock %}

mysite/orders/templates/orders/order/created.html
{% extends "goods/base.html" %}

{% block title %}Заказ успешно создан!{% endblock %}

{% block content %}
    <h1>Спасибо за заказ! :)</h1>
    <p>Заказ успешно оформлен. Номер вашего заказа
        <strong>#{{ order.id }}</strong>.</p>
{% endblock %}